version: '2'
services:

  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: secret

  orm:
    build:
      context: .
    volumes:
      - .:/usr/src/app
    environment:
      DB_PASSWORD: secret
      DB_HOST: postgres
    links:
      - db:postgres
